Imports Microsoft.Practices.EnterpriseLibrary.Logging.ExtraInformation
Imports Microsoft.Practices.EnterpriseLibrary.Logging.Filters
Imports PacificLife.Life

public class ThisAddIn
    '**********************************************************************
    '
    ' ThisAddin.vb
    '
    ' This class is required and is generated by the AddIn framework.
    ' It is responsible for hooking the AddIn to the events fired by
    ' Excel as different operations are performed.
    '
    ' Changes to this file are unlikely.  
    ' The action occurs in ExcelAppEvents.vb
    '
    '**********************************************************************

    Private _ExcelAppEvents As ExcelAppEvents

    Private Sub ThisAddIn_Startup(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Startup
        PLLog.Trace5("Enter", Globals.cPLLOG_NAME)

        Try
            _ExcelAppEvents = New ExcelAppEvents
            _ExcelAppEvents.ExcelAppEvent = Globals.ThisAddIn.Application
        Catch ex As Exception
            PLLog.Error(ex, Globals.cPLLOG_NAME)
        End Try

        PLLog.Trace5("Exit", Globals.cPLLOG_NAME)
    End Sub

    Private Sub ThisAddIn_Shutdown(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Shutdown
        PLLog.Trace5("Enter", Globals.cPLLOG_NAME)

        Try
            _ExcelAppEvents = Nothing
        Catch ex As Exception
            PLLog.Error(ex, Globals.cPLLOG_NAME)
        End Try

        PLLog.Trace5("Exit", Globals.cPLLOG_NAME)
    End Sub

    Protected Overrides Sub Finalize()
        MyBase.Finalize()
    End Sub
End Class
